### ISSUE TITLE
[bug] roles - Roles are not easily manageable

### ISSUE THREAD

**Issue by funcyChaos** [freedit-org/freedit#190]
I can see different roles as an enum as well as here and there in the code base, for authentication and controllers
I don't see a way to assign a role to a user or what the default role for new users would be
I also don't see a way to adjust the ability of roles, like to disallow them from making new Inns

I am still a bit new to `MVC` and I am new to Rust, but I am familiar with C and C++ which feels at least similar. 
I will look into solving this for myself, but would appreciate either advise or any other direction

Cheers,
Funcy

**Comment by freedit-dev** [comment]
https://github.com/freedit-org/freedit/issues/98

Yeah, almost everything is hard-coded. I did have a plan to refactor this part, but I need more info to architect it properly.

**Comment by funcyChaos** [comment]
Let me know if I can help? I definitely think it could  be built pretty similarly to wordpress (:eyes:)

**Comment by freedit-dev** [comment]
Thanks for your feedback. The role-based access control is a feature that I'm working on. And there is a crate called [oso](https://github.com/osohq/oso) that might be helpful. The problem is that freedit is lack of users, so I don't know which access should be controlled.

https://freedit-org.github.io/freedit/freedit/controller/struct.User.html#permissions

https://freedit-org.github.io/freedit/freedit/controller/inn/index.html#permissions
